version: "3.9"

services:
  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: parkinglot
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - parkinglotNetwork

  parkinglot:
    image: 'parkinglot:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parkinglot
    restart: on-failure
    ports:
      - "1222:1222"
    environment:
      - server.port=1222
      - spring.datasource.username=root
      - spring.datasource.password=password
      - PARKING_LOT_DB_IP=database
      - PARKING_LOT_DB_PORT=3307
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/parkinglot
    depends_on:
      - database
    networks:
      - parkinglotNetwork

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - parkinglotNetwork

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - parkinglotNetwork


networks:
  parkinglotNetwork: